### PR TITLE
Python3 support

### LINKED ISSUE #2: Add Python 3 support
Although Python 2 will still be supported for quite some time, [Ubuntu plans to remove Python 2](https://wiki.ubuntu.com/Python/FoundationsXPythonVersions) from the standard installation in 16.04, so this might be a good time to get Python 3 support ;-)

### PR DESCRIPTION
**Pull request by Holzhaus**
Partially resolves #2. This does not work yet, since `pymadfile.c` still needs to be ported over.

### CODE REVIEW

**Comment by jaqx0r** [comment]
I have a noob question: is this backwards compatible with python 2?

**Comment by Holzhaus** [comment]
Yes. There are some incompatible changes in the C api, but you can easily use `#if PY_MAJOR_VERSION >= 3`/`#endif`.

**Comment by jaqx0r** [comment]
Would you mind adding those ifdefs?

**Comment by Holzhaus** [comment]
They're already there: https://github.com/jaqx0r/pymad/pull/3/files#diff-8f27d98fac807dee0feb52d1b789937bR15

Still trying to figure out how to port `pymadfile.c` though

**Comment by Holzhaus** [comment]
OK, I ported the `pymadfile.c`. This doesn't work yet though, since they changed the buffer interface (`PyBuffer_new` doesn't exists anymore) and I'm not that competent in using the Python C API. I tried to make the read method simply return bytes, but to no avail.

Could you look into it? The new style buffer objects also exist in Python 2.6, so pymad could implement this without using loads of `#ifdef`.

**Comment by Holzhaus** [comment]
Here's the relevant documentation: https://docs.python.org/2/c-api/buffer.html

**Comment by jaqx0r** [comment]
Yep, sure. Thanks for the contribution!

**Comment by jaqx0r** [comment]
I'm trying to learn the "new" buffer api which works from 2.6 onwards. That
should simplify the code by only having one implementation and get python 3
support as well, but the docs are a bit difficult to follow so I'm not
making much progress yet.

**Pull request merged**
